services:
  app:
    build: .
    container_name: reto_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Define el perfil activo
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/reto_backend
      - SPRING_DATASOURCE_USERNAME=fundacion_antivirus
      - SPRING_DATASOURCE_PASSWORD=Antivirus
    depends_on:
      - db-mysql
    networks:
      - backend
    entrypoint: ["dockerize", "-wait", "tcp://db-mysql:3306", "-timeout", "30s", "java", "-jar", "app.jar"]

  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: reto_backend
      MYSQL_USER: fundacion_antivirus
      MYSQL_PASSWORD: Antivirus
    ports:
      - "53:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
